cesanta/mongoose

- mongoose.c
This also protect against the latest glibc bug
> Replace obsolete gethostbyname by getaddrinfo

- mongoose.c
Upstream patch from MAME project
> OS/2 patches by KO Myung-Hun

- mongoose.c
This was identified by out static analysis tools.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/494)
> Fixed Memory Leak

- mongoose.c
- mongoose.h
Closes #483
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/509)
> Fix mjpg_streamer example

- mongoose.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/550)
> Fix ssl close with polarssl

- examples/server_data_push/Makefile
- examples/server_data_push/server_data_push.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/561)
> Mongoose example for server data push

- examples/server_data_push/server_data_push.c
- mongoose.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/562)
> Swallow responses to internal pings

- examples/server_data_push/server_data_push.c
Put cases in the order we expect them to occur
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/563)
> Tweak event handler a bit for clarity

- jni/Android.mk
Fix for compile error in Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/678)
> !): Fix for compile error in Android.

- README.md
Download “9 Things NOT to do when embedding a web server” white paper.
> added MWS white paper

- mongoose.c
- src/mg_http.c
h/t @BushraAloraini
Fixes https://github.com/cesanta/mongoose/issues/1135
> Add missing range check in mg_get_http_header()

- docs/README.md
Fixed typos in Cesanta.com MWS docs
> Fixed typos

- mongoose.c
- src/url.c
- test/unit_test.c
> allow for in-url colon, when port is not specified

- mongoose.c
- mongoose.h
- src/arch_freertos_lwip.h
- src/fs_posix.c
- src/log.c
- src/sock.c
Fix small problems related to compilation on STM32/FREERTOS /LWIP platform
> Update FREERTOS + LWIP support

- docs/README.md
Describe parameters and return values of Mongoose API
> Add parameters descriptions to documentation

- mongoose.c
- mongoose.h
- src/arch.h
- src/arch_azurertos.h
- src/config.h
- src/sock.c
- src/util.c
Changes required for HTTP Server example work in AzureRTOS enviroment
> Add AzureRTOS basic support

- docs/README.md
I have gone through and edited for consistency, punctuation, wording, and grammar. If you have questions feel free to reach out.  I fixed some spelling errors "if" instead of "is" "update" instead of "updatw", etc. 
-Jordan Ramsey
> Update README - Jordan Ramsey Edits.md

- examples/http-reverse-proxy/main.c
Signed-off-by: yermin <yermin@buaa.edu.cn>
> makes it more readable

- src/tls_openssl.c
I'm pretty sure this was a left over from a debug session, i kept getting spammed in the log about hexdumps
> Remove debugging left over

- mongoose.c
- src/util.c
- test/unit_test.c
Should hopefully fix the random mqtt test failures.
> Ensure MQTT_CMD_SUBACK is received before calling mg_mqtt_pub in tests

- examples/http-proxy-client/Makefile
- examples/http-proxy-client/main.c
Fixed missing parameter in makefile
Added URI handling
> Added openSSL support

- examples/tcp/Makefile
- examples/tcp/main.c
> Added plain TCP server and client example

- examples/esp32/device-dashboard/Makefile
- examples/esp32/device-dashboard/README.md
Expanded Makefile to be able to flash with Docker and esputil
> Changed README to point to new tutorial location

- examples/esp8266/Makefile
- examples/esp8266/README.md
- examples/esp8266/src/main/main.c
> Improved Makefile to be able to flash

- examples/esp8266/Makefile
Sometimes the bootloader has to be updated
Logs are sent at a really odd baud rate
> Expanded Makefile

- mip/driver_stm32.c
- mongoose.c
a bit larger than I like... but perhaps worth it
> Extend explanation for MDC clock

- mongoose.c
> Bug Fix #1714

- test/mip_test.c
(used statics 'cause they make it easier to step by step)
line 26 will fail
> Make mip_test fail with current queue algo

- src/http.c
adding compile time option to display file modification date as "%Y/%m/%d %H:%M:%S" in http directory indexing.
> display file modify date in "%Y/%m/%d %H:%M:%S".

- examples/stm32/stm32-nucleo-f429z/Makefile
Added "flash" command
Allowed calling "build" once the repo has already been cloned
> Update Makefile as per the tutorial

- mongoose.c
- src/rpc.c
> Fix null pointer dereference in mg_rpc_add()

- .github/workflows/test.yml
- mongoose.c
- mongoose.h
- src/arch.h
- src/md5.c
- src/sha1.c
- test/unit_test.c
Should make it easier to track down failures due to big endian incompatible code.
> Test on big endian CPU architectures

- .github/workflows/test.yml
Some issues may be specific to 32 bit big-endian, lets test that as well.
> Also test on 32 bit big endian ppc

- examples/smtp-client/README.md
- examples/smtp-client/main.c
Remove extra EHLO before AUTH (there were two)
Remove references to gmail as it requires OAUTH2
> Fix wrong ca.pem path + 

- .github/workflows/test.yml
- test/unit_test.c
It appears there's a bunch of endian specific failing 32 bit tests.
> Disable broken 32 bit tests and enable 32 bit little endian tests.

- examples/json-rpc-over-websocket/web_root/rpc-over-websocket.js
Great library! Thanks for your work.
I noticed some bug in this example and fixed it.
Have a nice day
> Fix json-rpc-over-ws example

- examples/raspberry/raspberry-pi-pico-w/Makefile
> Make pico-w device-dashboard example fully functional

- mongoose.c
- mongoose.h
- src/arch_tirtos.h
- src/util.c
> Improve TI-RTOS timing support

- docs/README.md
> Augment WS documentation

- examples/ti/ek-tm4c1294xl-baremetal/Makefile
- examples/ti/ek-tm4c1294xl-baremetal/README.md
- examples/ti/ek-tm4c1294xl-baremetal/boot.c
- examples/ti/ek-tm4c1294xl-baremetal/link.ld
- examples/ti/ek-tm4c1294xl-baremetal/main.c
- examples/ti/ek-tm4c1294xl-baremetal/mcu.h
- examples/ti/ek-tm4c1294xl-baremetal/syscalls.c
> Add EK-TM4C1294XL example

- examples/arduino/w5500/w5500.ino
- examples/mip-pcap/main.c
- examples/mip-tap/main.c
- examples/stm32/nucleo-f429zi-baremetal/main.c
- examples/stm32/nucleo-f429zi-freertos-mip/main.c
- examples/stm32/nucleo-f746zg-baremetal/main.c
- examples/ti/ek-tm4c1294xl-baremetal/main.c
00:00:01 is Xerox's OUI.
MACs starting with 02: (and others) are locally administered
> change MIP MAC to LAA

- examples/stm32/nucleo-f746zg-freertos-mip/FreeRTOSConfig.h
- examples/stm32/nucleo-f746zg-freertos-mip/Makefile
- examples/stm32/nucleo-f746zg-freertos-mip/README.md
- examples/stm32/nucleo-f746zg-freertos-mip/boot.c
- examples/stm32/nucleo-f746zg-freertos-mip/link.ld
- examples/stm32/nucleo-f746zg-freertos-mip/main.c
- examples/stm32/nucleo-f746zg-freertos-mip/mcu.h
- examples/stm32/nucleo-f746zg-freertos-mip/mongoose_custom.h
- examples/stm32/nucleo-f746zg-freertos-mip/syscalls.c
Links in README will work when the tools tutorial gets merged
> Add FreeRTOS + MIP example on F746

- .github/workflows/test.yml
- test/mip_test.c
- test/setup_ga_network.sh
Included github actions tests for MIP using TUNTAP device.
> Release MIP tests using tuntap

- docs/README.md
- mip/mip.c
- mongoose.c
- src/fmt.c
Add %A to print hw address and use it in mip.c
Fix some debug data
> Use %I in mip.c

- examples/mip-tap/main.c
- test/mip_tap_test.c
Tuntap related calls modified to compile natively on OpenBSD.
> Mip tests and tuntap example to compile on OpenBSD natively.

- examples/mqtt-server/main.c
> Fix MQTT server example

- mip/mip.c
- mongoose.c
When delaying ACKs, start counting on the first incoming segment instead of the last one.
We should actually also ACK when our window has been exhausted but that is a bit more involved
> Don't retrigger ACK timer

- examples/stm32/nucleo-f429zi-freertos-mip/mcu.h
- examples/stm32/nucleo-f429zi-usb-rndis/mcu.h
- examples/stm32/nucleo-f746zg-baremetal/mcu.h
- examples/stm32/nucleo-f746zg-freertos-mip/mcu.h
- examples/stm32/nucleo-f746zg-usb-rndis/mcu.h
Fixed F4 and F7. Checked H7 has the same AF, future copypaste is safe.
Complements https://github.com/cesanta/mongoose/commit/556bf7b88887934002f456f623bf0e05349666b9
> Fix AF in UART1,2

- examples/ti/ek-tm4c1294xl-baremetal/Makefile
- examples/ti/ek-tm4c1294xl-baremetal/README.md
- examples/ti/ek-tm4c1294xl-freertos-mip/README.md
> Get rid of Docker (TI), part 1

- examples/stm32/nucleo-f429zi-freertos-mip/FreeRTOSConfig.h
- examples/stm32/nucleo-f429zi-freertos-mip/main.c
- examples/stm32/nucleo-f429zi-freertos-mip/mcu.h
- examples/stm32/nucleo-f429zi-usb-rndis/main.c
- examples/stm32/nucleo-f429zi-usb-rndis/mcu.h
- examples/stm32/nucleo-f746zg-baremetal/main.c
- examples/stm32/nucleo-f746zg-baremetal/mcu.h
- examples/stm32/nucleo-f746zg-freertos-mip/FreeRTOSConfig.h
- examples/stm32/nucleo-f746zg-freertos-mip/main.c
- examples/stm32/nucleo-f746zg-freertos-mip/mcu.h
- examples/stm32/nucleo-f746zg-usb-rndis/main.c
- examples/stm32/nucleo-f746zg-usb-rndis/mcu.h
> Fix UART1,2 clocking in all other examples

- docs/README.md
> Revert "fix the doc error: htts to https"

- examples/websocket-server/main.c
> Revert "Update comment for the path of rest API"

- mongoose.c
- mongoose.h
- src/net.c
- src/net.h
- src/util.c
- src/util.h
Move net print utility functions to util
#1997
> Add mg_print_mac()

- mip/driver_stm32.c
- mip/driver_tm4c.c
- mongoose.c
Registers 31 and 16 are vendor specific, they depend on the PHY being used.
STM: I used LAN8720/24 as in the dev boards
TM4C: it is a built-in PHY
> Add support for 10M and half-duplex in STM32 and TM4C drivers

- docs/README.md
- mongoose.c
- src/fmt.c
closes #1996 
closes #1997
closes #2006 
closes #2015
> Docs update, remove %I and %A extensions

- examples/stm32/nucleo-f746zg-baremetal/Makefile
- examples/stm32/nucleo-f746zg-baremetal/hal.h
- examples/stm32/nucleo-f746zg-baremetal/main.c
- examples/stm32/nucleo-f746zg-baremetal/sysinit.c
- mip/driver_stm32.c
- mip/mip.c
- mip/mip.h
- mongoose.c
- mongoose.h
> Introduce sysinit.c, better debug log, more verbose Makefile

- test/unit_test.c
> Add coverage

- test/unit_test.c
> Test coverage

- src/tcpip/driver_nxpimxrt1020.c
- src/tcpip/driver_nxpimxrt1020.h
- src/tcpip/tcpip.h
Baremetal iMX RT1020 driver, MG_TCPIP
> mg_tcpip_imxrt1020

- test/unit_test.c
Add completion for 2 functions.
> add coverage ws.c

- src/tcpip/driver_nxpimxrt1020.c
Rename from structs and functions.
> Fix build mip -> mg_tcpip

- examples/http-client/Makefile
- examples/http-server/Makefile
Do you agree to use these final Makefiles as golden references for:
no TLS: http-server
TLS: http-client
?
I will add all the OS-dependent mumbo jumbo for the command line calls to the TLS tutorial and update all references in all other TLS-related tutorials to just link there.
> Golden Makefiles

- src/tcpip/driver_nxpimxrt1020.c
Driver processes non truncated frames with a valid CRC.
> rt1020 driver check frame crc/truncated

- examples/rp2040/pico-rmii/driver_rp2040_rmii.c
- examples/rp2040/pico-rndis-dashboard/main.c
- examples/stm32/nucleo-f429zi-rndis/main.c
- examples/stm32/nucleo-f746zg-rndis/main.c
- src/tcpip/tcpip.h
workflow in #2076 did not detect build problems. Fixed in #2094 , tested here
> Fix RNDIS examples

- .github/workflows/test.yml
- Makefile
> Test some examples on Windows

- examples/rp2040/pico-w5500/main.c
Added MAC generation from board_id (which comes from the board 's flash ID)
Standardized example texts and structure
> Gen MAC from board ID, standardize

- test/unit_test.c
> Test TLS host verif with no CA

- Makefile
- mongoose.c
- mongoose.h
- src/dns.c
- src/event.c
- src/fmt.c
- src/fmt.h
- src/fs.c
- src/fs_packed.c
- src/http.c
- src/net.c
- src/printf.c
- src/printf.h
- src/sock.c
- src/ssi.c
- src/tls_mbed.c
- src/tls_openssl.c
- src/util.h
- src/ws.c
> Add printf.h

- mongoose.c
- src/fs_fat.c
- src/fs_packed.c
> Check for calloc() failure in filesystem code

- mongoose.c
- src/sock.c
- test/unit_test.c
> fix bind issue in W

- Makefile
Make the Makefile more Linux distro-package friendly as per #2203 :
- Remove hardcoded /lib and /include and let them be specified
- Add to a possibly specified LDFLAGS 
( closes #2203 )
> make more distro-friendly

- examples/device-dashboard/net.c
Confirmed working on hardware (HTTP), Linux and MIP-TAP (HTTP/HTTPS)
> Fix Secure

- mongoose.c
- src/http.c
- test/unit_test.c
> fix header truncation

- test/unit_test.c
bring back host name validation with no CA nor certs
> add host only validation

- src/fs_posix.c
> Do not use CLOEXEC on Windows

- .github/workflows/test.yml
- examples/nxp/rt1020-evk-make-baremetal-builtin/Makefile
- examples/nxp/rt1020-evk-make-baremetal-builtin/hal.h
- examples/nxp/rt1020-evk-make-baremetal-builtin/main.c
- mongoose.c
- mongoose.h
- src/drivers/rt1020.c
- src/drivers/rt1020.h
Add web server in example
Add to tests
> Rework  RT1020 driver

- test/unit_test.c
Split MQTT tests in two functions, first one connects with no options, hence it is only v3.1.1. Second function is then called once for v3.1.1 specific tests and then for v5 tests
> improve MQTT test speed

- mongoose.c
- src/sock.c
> Allow fast close

- mongoose.c
- src/tls_builtin.c
Not much there, but at least it builds now
> Make tls_builtin build with current API

- mongoose.c
- src/tls_openssl.c
> Wrap OpenSSL errors in Mongoose log

- .github/workflows/test.yml
Installing armgcc takes time
Downloading each example takes a lot of time
Only do hardware tests on those examples that have changed (or Mongoose have changed). Only for F7 so far.
> test specific hw example

- mongoose.c
- src/net_builtin.c
> Be less verbose on unkown eth types

- mongoose.c
- src/drivers/imxrt.c
- src/drivers/same54.c
- src/drivers/stm32f.c
- src/drivers/stm32h.c
> prefix PHY-related constants

- mongoose.h
- src/arch_zephyr.h
> Zephyr fcntl

- mongoose.c
- src/net_builtin.c
> poll TLS to process outstanding data in receive buffer

- src/sock.c
Fixes #2719 (see [comment](https://github.com/cesanta/mongoose/issues/2719#issuecomment-2072530370))
> TLS corner cases

- examples/rp2040/pico-rndis-device/main.c
- examples/stm32/nucleo-h723zg-make-baremetal-builtin/main.c
- mongoose.c
- mongoose.h
- src/arch_freertos.h
- src/arch_rtx.h
- src/http.c
- src/mqtt.c
- src/net.c
- src/rpc.c
- src/str.c
- src/str.h
- src/tls_builtin.c
- src/tls_mbed.c
- src/util.c
- src/util.h
- test/fuzz.c
- test/mip_tap_test.c
- test/unit_test.c
- tutorials/core/multi-threaded/main.c
- tutorials/mqtt/mqtt-server/main.c
- tutorials/udp/ssdp-search/main.c
> cleanup 'str' API

- mongoose.c
- mongoose.h
- src/drivers/stm32h.c
- src/drivers/stm32h.h
First approach with minimum changes, tested on MCXN947
> Move stm32h driver to synopsys

- mongoose.c
- src/tls_openssl.c
> play nicer to intermediate OOMs in OpenSSL

- mongoose.c
- src/http.c
- test/unit_test.c
> resume pipelined reqs after serving a file

- mongoose.c
- src/http.c
- test/unit_test.c
> fix 411 not draining header data

- mongoose.c
- src/tls_openssl.c
> SSLv23_ methods deprecated

- mongoose.c
- src/ws.c
> handle possible memory trashing on mg_send() and mg_iobuf_add() failures

- mongoose.c
- src/sock.c
> make friends with FreeRTOS+TCP compatibility

- mongoose.c
- mongoose.h
- src/net.h
- src/sock.c
> improve close on TLS

- mongoose.c
- src/net_builtin.c
> fix ARP resolution when remote host is the gw

- mongoose.c
- src/fmt.c
- test/unit_test.c
> fix printf precision handling

- test/cgt+make/Makefile
- test/cube/Makefile
- test/wizard/Makefile
- test/wizard/test.sh
> Add test Makefiles for more IDEs

- mongoose.c
- mongoose.h
- src/net_builtin.c
- src/net_builtin.h
- tutorials/tcpip/pcap-driver/main.c
@cpq For some reason you added this branch, and it was left behind. Rebased.
> Fix gw ARP. Make ARP probe public. Add ARP event

- mongoose.c
- src/http.c
> Honor c->is_resp with Connection:close

- examples/device-dashboard/net.c
- examples/wifi-router-dashboard/net.c
- reference-projects/windows-macos-linux/web-ui-dashboard/net.c
> Use separate cookies for HTTP and HTTPS connections

- tutorials/websocket/websocket-server/Makefile
- tutorials/websocket/websocket-server/main.c
match client: add command line args, default to built-in TLS
> add TLS support

- mongoose.h
- src/arch_win32.h
- src/config.h
> allow other stack than WinSock in Windows

- mongoose.c
- mongoose.h
- src/sock.c
- src/tls_mbed.c
Fixes #3104
MbedTLS API fairplay
> Fix not reading last TLS small record with fast closure

- tutorials/zephyr/Makefile
- tutorials/zephyr/device-dashboard/src/main.c
- tutorials/zephyr/http-client/src/main.c
- tutorials/zephyr/http-server/src/main.c
- tutorials/zephyr/mqtt-aws-client/src/main.c
- tutorials/zephyr/websocket-server/src/main.c
> Improve 4.2 test time

- mongoose.c
- src/net_builtin.c
- test/mip_test.c
Add unit tests for TCP error handling
Account for options in TCP header for payload start address calculation
Take UDP payload length from UDP header
> Fix TCP error handling

- mongoose.c
- src/tls_builtin.c
- test/unit_test.c
> Fix 2-way auth, fix skip hostname validation
