cesanta/mongoose

mongoose.c

Fixes the build on NetBSD.
The comment says it's only needed on Linux, and AFAIK Linux
is the only operating system that only adds symbols when it's defined;
others, like NetBSD or Solaris, also hide symbols.
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>

Only define _XOPEN_SOURCE on Linux.

---

mongoose.c

This adds #include \<Ws2tcpip.h\>, which is required for IPv6 support in VS9.
Also, VS9 does not allow c99 in-block declarations, so there's a change to move an assignment to be after some const declarations.
Tested with VS 2008 x86 and VS 2013 x64 (and x86) by running:
mhttpd.exe -listening_port "[::1]:8080"
Tested with IE11 and Chrome 40.

Allow for compilation in Visual Studio with NS_ENABLE_IPV6.

---

examples/websocket_ssl_proxy/Makefile

Hi @cpq.
I've adopted websocket_ssl_proxy (its makefile) sample for polarssl.
By default (i.e. `make`) it builds with openssl. 
To build against polarssl use `make polarssl`
I prepared makefile for polar/polar_compat as well, I'll send PR then this one will be merged coz they are linked. 
As you can see, I've sent PR to master. I think we should make all changes here and then backport to another places (?).
Web_server will be next, I've started from websocket_ssl_proxy coz it was already completed, I've just changed makefile

websocket_ssl_proxy sample for polarsll

---

mongoose.c
mongoose.h

I use mongoose in my program (https://bitbucket.org/dmilligan/mlvfs), it's really great and easy to use, thanks for all the hard work! 
I compile for 64-bit and I get a lot of compiler warnings, mostly due to the fact that int and size_t are sometimes used interchangeably in mongoose, but on 64-bit systems they are different sizes. Mostly this is just a matter of correcting function prototypes or variable declarations. I see you are already using size_t somewhat, so I assume this won't cause any issues. I did need to use uintptr_t in one place to be technically correct (since size_t isn't necessarily uint64_t even on 64 bit systems, though it is usually), but IDK how portable that definition is.

fix compiler warnings for 64 bit compilation

---

mongoose.c

The PATCH method is often used in REST API's.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/492)

Added PATCH to list of valid HTTP Methods.

---

mongoose.c

Note that in Android NDK st_mtime is long unsigned int
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/495)

OS2 and Android NDK fixes

---

mongoose.c

reported by the clang static analyser ... note that the fault path might be incomplete (perhaps the error should be reported up instead of just ignoring it)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/501)

safety belt : scan_directory() can return without setting arr to a valid value

---

mongoose.c

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/504)

Reverting (socket < 0) checks to avoid Windows build failure.

---

docs/ReleaseNotes.md
mongoose.c

In mg_get_var() the first call of get_var() inspects the variables of the query string. If the requested variable is found but the destination buffer is too small to hold the variable, return -2 right away. If it's not found, make the second call of get_var() to inspect the POST buffer.
What happens now: if the destination buffer is too small to hold the value of a variable from the query string, the POST buffer is inspected. If the variable is not found in the POST buffer, -1 is returned. Thus, it looks as if the variable wasn't found at all, which is not true.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/505)

Inspect POST buffer in mg_get_var() only if first call of get_var() returns -1

---

mongoose.c

https://support.microsoft.com/en-us/kb/111855 describes
that the user is expected to set the FD_SETSIZE macro
before including winsock2.h
It turns out to be very confusing and it's aggravated by
the fact that the default (64) far from being remotely practical.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/514)

Fix default windows FD_SETSIZE, closes #506

---

mongoose.c
mongoose.h

The commit adds `mg_vprintf` and `mg_vprintf_data` in order to have the `va_list` like functions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/525)

Adding mg_vprintf and mg_vprintf_data.

---

examples/array_vars/Makefile
examples/array_vars/array_vars.c
mongoose.c
mongoose.h

Mongoose didn't implement a way for retrieving array variables like:
```
http://www.example.com?foo[]=1&foo[]=2&foo[]=3
```
If you try to get them through `mg_get_var` you only get the first one. This patch implements `mg_get_n_var` which gets the `n` aparition of the desired var. An exmaple of how to use it is in `examples/array_vars`.
The basic idea is to iterate using `mg_get_n_var` until the function returns `-1`, which means that no more array value was found. E.g.:
```
// Supposing this is called inside an ev_handler.
// conn is a valid mg_connection
char buffer[1024];
int ret,
i;
for(i=0; (ret = mg_get_n_var(conn, "foo[]", buffer, 1024, i)) > 0; i++)
mg_printf_data(conn, "\nfoo[%d] = %s", i, buffer);
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …

Implementing array varibles

---

mongoose.c

I have run into a leak problem while using `connection_params`. My example is like this (it's the [hello_world example](https://github.com/cesanta/mongoose/blob/master/examples/hello_world/hello_world.c) with some modifications):
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mongoose.h"
int running = 1;
static int ev_handler(struct mg_connection *conn, enum mg_event ev) {
if(conn->connection_param == NULL){
printf("allocating memory\n");
conn->connection_param = malloc(1000);
}
switch (ev) {
case MG_AUTH: return MG_TRUE;
case MG_REQUEST:
mg_printf_data(conn, "Hello! Requested URI is [%s]", conn->uri);
if(strcmp(conn->uri, "/exit") == 0)
running = 0;
return MG_TRUE;
case MG_POLL:
printf("poll\n");
return MG_FALSE;
case MG_CLOSE:
if(conn->connection_param){ …
```

Possible fix in order not to loose the reference of connection_param pointer

---

mongoose.c

This patch fixes the following VS2013 compiler warnings:
- mongoose.c(659): error C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead
- mongoose.c(46): warning C4005: '_MBCS' : macro redefinition
- mongoose.c(3895): warning C4244: 'initializing' : conversion from 'int64_t' to 'size_t', possible loss of data
- mongoose.c(4804): warning C4244: 'initializing' : conversion from 'int64_t' to 'size_t', possible loss of data
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/mongoose/556)

Fix VS2013 warnings

---

examples/cookie_auth/cookie_auth.c

The ASAN build fails for examples/cookie_auth with
```
cookie_auth.c:62:7: error: variable 'ret' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
if (cookie_header == NULL) goto clean;
^~~~~~~~~~~~~~~~~~~~~
cookie_auth.c:84:10: note: uninitialized use occurs here
return ret;
^~~
cookie_auth.c:62:3: note: remove the 'if' if its condition is always false
if (cookie_header == NULL) goto clean;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cookie_auth.c:65:3: note: variable 'ret' is declared here
struct session *ret = NULL;
^
cookie_auth.c:62:7: error: variable 'ssid' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
if (cookie_header == NULL) goto clean;
^~~~~~~~~~~~~~~~~~~~~
cookie_auth.c:81:7: note: uninitialized use …
```

Fix ASAN build for examples/cookie_auth

---

tools/README.md

Hey,
my previous pull request #982 was closed. The main issue (the broken preview image) was fixed, but the typo still exists in `tools/README.md`. This PR fixes just that typo.

fix typo in tools/README.md

---

mongoose.c
src/common/cs_dbg.c

In implementatiosn that have preemptive scheduelrs these can be implemented
to ensure logging from different threads is properly serialized.

Add cs_log_{lock,unlock}

---

mongoose.c
mongoose.h
src/.clang-format
src/common/str_util.c
src/common/str_util.h
src/mg_http.c
src/mg_http.h
src/mg_util.c
src/mg_util.h
test/.clang-format
test/Makefile
test/unit_test.c
tools/README.md

Move to mg_util.h so encode and decode are next ot each other.
Pull out mg_next_list_entry_n() for advanced use cases.
Add unit tests.

Add mg_next_query_string_entry_n() and mg_url_decode_n()

---

mongoose.c
src/tls.c

This PR suppresses the error `cast from ‘void*’ to ‘int’ loses precision [-fpermissive]` in the MG_ENABLE_OPENSSL build.
The cast from `void *` to `int` is illegal in some modern compilers (GCC, Clang). Casting to `ssize_t` is still legal.

Suppress error: cast from ‘void*’ to ‘int’ loses precision [-fpermissive] in MG_ENABLE_OPENSSL build.

---

mongoose.c
src/tls.c

Provide possibility to parse `opts->cert` and `opts->certkey` from buffer.
Adds functionality proposed in issue #1240 .

mbedtls parse cert and key from buffer

---

mongoose.c
src/tls.c

MSVC doesn't like VLAs (e.g. https://gcc.godbolt.org/z/Kn6n4TzaP), which means mongoose won't compile with MSVC if using mbedtls or openssl. This resolves it by using a dynamic allocation.
Original errors from mongoose compile with VS2019:
```
mongoose.c(3671,35): error C2057: expected constant expression
mongoose.c(3671,35): error C2466: cannot allocate an array of constant size 0
mongoose.c(3671,36): error C2133: 'buf': unknown size
```

fixed msvc errors around VLAs when using TLS

---

.github/issue_template.md

As it is in the discussion of raised issues to have some extra iteration because of architecture, library version, and other meta information, an issue template could save these extra rounds and possibly reduce the number of duplicates by highlighting where one can check for answers.
This is just a sketch based on what notifications I got from mongoose in the past months. Feel free to change it.

Propose an issue template

---

Makefile

I know that the topic has come up a few times already (e.g. https://github.com/cesanta/mongoose/issues/326) and I understand you, as the maintainers, understand mongoose source code to be simply added to an existing project.
However, I believe that packaging mongoose as a separate lib does have its advantages, e.g. when packaging it for a Linux distro, e.g. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mongoose or https://github.com/iris-GmbH/meta-iris-thirdparty/blob/feature/jaor/mongoose_recipe/recipes-core/mongoose/mongoose_7.2.bb. For the latter I extended the existing Makefile in what I believe to be a pretty unintrusive way.
I'd be happy if you would reconsider adding support for building mongoose as a library. If not, so be it. No hard feelings :slightly_smiling_face:

Add static and dynamic lib targets to Makefile

---

Makefile

Esthetic change which replaces the curly brackets introduced by me in
commit b6ee9e637bbb885c29291f3fcc632b05375f6b28 with round brackets.
Because consistency.

Makefile: change curly brackets to round brackets

---

examples/http-reverse-proxy/main.c

And I believe it's right. Other-side-close should be done only for the 'A' (proxy-client-side) connection.

The sanitiser pointed out this problem

---

mongoose.c
src/http.c
test/unit_test.c

Fix a copy/paste error, which resulted in only short (<0x10) chunks being handled as expected.
Fixes #1340 .
Out of curiosity I cut out the relevant parts of the code to godbolt.org and enabled PVS Studio to see whether their (excellent) copy-paste detector would throw a warning: https://godbolt.org/z/bP1P93faE
But it didn't :( 
Anyway, it would be interesting to register this project to their Open Source free service, in other projects I have seen wonders from this tool:
https://pvs-studio.com/en/blog/posts/0614/

Fix #1340: Long HTTP Chunks

---

examples/stm32-freertos-tcp/stm32f7/core_cm7.h

There is a small typo in examples/stm32-freertos-tcp/stm32f7/core_cm7.h.
Should read `priority` rather than `priorty`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, priorty -> priority

---

Makefile

Should help prevent some spurious test failures due to stale `test/packed_fs.c` file.

Regenerate pack file when dependencies are changed.

---

.github/workflows/test.yml
Makefile

Per valgrind docs:
> If you are planning to use Memcheck: On rare occasions, compiler optimisations (at -O2 and above, and sometimes -O1) have been observed to generate code which fools Memcheck into wrongly reporting uninitialised value errors, or missing uninitialised value errors.
> So the best solution is to turn off optimisation altogether.
Also cleaned up the tests(some weren't getting run properly like `test++`) using the test matrix feature.

Run valgrind tests with appropriate compiler optimizations.

---

test/unit_test.c

This test seems to fail randomly a lot, print the buffer on error to make it easier to isolate issues.

Print mqtt buffer on error in tests

---

test/mongoose_custom.c

Fixes:
```c
test/mongoose_custom.c:26:6: error: conflicting types for 'mg_mgr_wakeup'
26 | void mg_mgr_wakeup(struct mg_connection *c, const void *buf, size_t len) {
|      ^~~~~~~~~~~~~
In file included from test/mongoose_custom.c:1:
./mongoose.h:956:6: note: previous declaration of 'mg_mgr_wakeup' was here
956 | bool mg_mgr_wakeup(struct mg_connection *pipe, const void *buf, size_t len);
|      ^~~~~~~~~~~~~
make: *** [Makefile:105: arm] Error 1
```

Fix mg_mgr_wakeup conflicting types error

---

mongoose.c
src/sock.c
src/tls_mbed.c

mbedtls expects this to be returned if the connection resets.

Handle MBEDTLS_ERR_NET_CONN_RESET errors

---

mongoose.c
mongoose.h
src/arch_unix.h
src/config.h
src/sock.c

This adds the ability to substitute `select()` with `poll()` on supported
unix environments when `MG_ENABLE_POLL` is defined. A make flag called
`USE_POLL` is provided as well.
Using `poll()` removes the limitation of `FD_SETSIZE` concurrent sockets,
generally 1024 on Linux environments.
Tested with `make test IPV6=0 USE_POLL=1`
Marked as `draft` because I have not debugged a strange issue where substituting the call to `malloc()` in `mg_iotest()` with `alloca()` (as suggested by @cpq) results in the `test_http_client` and `test_dns_error` tests to fail.

Add optional poll() implementation under MG_ENABLE_POLL define

---

docs/README.md

The return value was not documented.

Small fix to mg_timer_add() documentation

---

src/http.c

in very large HTTP response, this offset might cause a problem with HTTP header format.

fixing offset of Content-Length value.

---

examples/mqtt-client/main.c
examples/timers/main.c

Timer time was 300ms but msgs came out at 1s 'cause mgr poll timeout was 1s
As 300ms looks too fast, I kept 1s for msg time and reduced poll time to 500ms

fixed poll timeout being larger than timer period 

---

examples/mqtt-over-ws-client/main.c

Only the first command (subscribe) succeeded.
7.7 has this same issue
Regarding failed checks: I've run my debug session, more info via mail

fix incorrect WS packet payload

---

mongoose.c
src/util.c

`CLOCK_MONOTONIC_RAW` on OSX is not the same as `CLOCK_MONOTONIC_RAW` on linux

util: use correct clock on OSX

---

mongoose.c
mongoose.h
src/mqtt.c
src/mqtt.h

Since already exported MQTT_CMD_* are also not prefixed with MG_, I left them as they are.
Let me know if you want to prefix something.

Exported MQTT result codes

---

mongoose.c
src/sntp.c

this is a fix for https://github.com/cesanta/mongoose/issues/1628

NTP reponse gives fractional (not micro-) seconds, per RFC5905

---

mongoose.c
src/json.c
test/unit_test.c

A key present in a later nested object was being incorrectly accepted, e.g.:
searching for `$a.b2` in `{"a": {"b1": {}}, "c": 7, "d": {"b2": {}}}`  returned `d.b2`
Modified test string
`const char *s2 = "{\"a\":{\"b1\":{}},\"c\":7}";` to
`const char *s2 = "{\"a\":{\"b1\":{}},\"c\":7,\"d\":{\"b2\":{}}}";`,
in order to catch it with  `ASSERT(mg_json_get(s2, n2, "$.a.b2", &n) == MG_JSON_NOT_FOUND);` failing; and fixed so now it passes.

Fix json's MG_EOO in nested objects

---

examples/esp32/uart-bridge/Makefile

Added a .PHONY target because _make flash_ wasn't always working
Added -p to esputil options to correctly support configuring the port using the PORT environment variable

Fix Makefile

---

examples/esp32/uart-bridge/Makefile
examples/esp32/uart-bridge/main/cli.c
examples/esp32/uart-bridge/main/main.c
examples/esp32/uart-bridge/main/main.h

The iobuf wasn't being explicitly initialized, it defaulted to 0 size and the _add() call was used to set a 32-byte alignment (from first call). Added a cli_init() function to be able to initialize alignment at 32 bytes; and called this function before entering the infinite loop.
Makefile: I think the phony target should be build, since there is a 'build' directory

Fix for new mg_iobuf API

---

examples/device-dashboard/net.c

ESP32 example relies on packed_fs, it links to it and not to the web_root dir

device-dashboard: default to using packed fs, otherwise hw examples won't work

---

examples/device-dashboard/net.c

MSVC does not like such empty initializer. Error is:
```
examples/device-dashboard/net.c(116): error C2059: syntax error: '}'
```

Fix empty initializer

---

examples/stm32/nucleo-f746zg-baremetal/README.md
examples/stm32/nucleo-f746zg-baremetal/boot.c
examples/stm32/nucleo-f746zg-baremetal/main.c

Changed README to use picocom as cu is apparently not able to add carriage return after line feed

Workaround for aliased weak symbol override issue

---

examples/multi-threaded/main.c

As we've got a question on this

Show how to send data to a worker thread

---

examples/stm32/nucleo-f746zg-baremetal/mcu.h

Rolled back the UART baud rate config:
APB2_PRE is 4 and that means APB2 clock will be /2
APB1_PRE is 5 and that means APB1 clock will be /4
We are using UART3, which uses APB1. The value of APB2_PRE was just a coincidence and changing it won't change the UART3 clock so our calculations would be wrong.
Proper setup would require a table lookup.

Group clock setup dependencies

---

mongoose.c
test/unit_test.c

Because **ci** is pre-added, when array ends, it needs to be decremented by 1  before  entering the macro **MG_EOO**.
Before this modification,  finding "$.a[1]"in {"a":[1],"b":[2,3]}" would got the result b[0] .

Fix mg_json_get for the array element result not as expected.

---

mip/driver_stm32.c
mongoose.c

The MDC clock is generated from the HCLK (AHB bus clock).
As per 802.3, it must not exceed 2.5MHz.
As the AHB clock can be (and usually is) derived from the HSI (internal RC), and it can go above specs, the datasheets specify a range of frequencies and activate one of a series of dividers to keep the MDC clock safely below 2.5MHz.
I wrote a simple set of functions to calculate the HCLK from current settings and then guess the CR value based on that clock with a 5% tolerance (these clocks are specified at 4,5% worst case).
If the user uses a different clock from our defaults, needs to set a macro: MG_STM32_CLK_HSE for external clock freq and MG_STM32_CLK_HSI for internal.
This is valid for the F4xx and F7xx. The H7xx has a different PLL structure and the MAC controller has a different …

Add CR setup, set MDC based on HCLK

---

mip/mip.c
mongoose.c

Disabling sending immediate ACKs works as long as there is something to send.
When the device starts, it connects to the MQTT broker and then subscribes to a topic. The MQTT SUB carries the TCP ACK to the MQTT CONNACK, but there is no traffic to carry the TCP ACK to the MQTT SUBACK.
The TCP ACK to the MQTT SUBACK is not sent and 800ms later the broker retransmits the TCP segment. MIP logs an OOB error, closes the connection and retries. This happens forever.
I could not re-enable sending the ACKs so moved that part to the calling function and returned a flag to signal the need to send an ACK "later". Since there is no timer in place, it is sent immediately.
Unnecessary ACKs are sent, but at least the connections don't break when idle.

Re-enable sending ACKs until proper mechanism is in place

---

mip/mip.c

1500 bytes is payload size, which is OK for tx. On the rx side, a full 802.1Q-tagged frame size is 1522 bytes. Without the 4-byte CRC = 1518 bytes (1514 for non-VLAN-tagged frames).

Fix Ethernet buffer size

---

mip/driver_stm32.c
mip/mip.c
mip/mip.h
mongoose.c
mongoose.h

ETH IRQ and mip_poll() can both write to the queue, so if a memcpy() is interrupted we might see some weird records.
I promise to run clang-format next time... sometimes it needs some massage and this was one of those.

Add rudimentary queue profiler

---

mip/mip.c
mip/mip.h
mongoose.c
mongoose.h

read access to drop_ctr should always be atomic except on some 8-bitters, which we don't support.

Add irq and drop counters to qprofiler

---

examples/mip-tap/Makefile
examples/mip-tap/README.md
examples/mip-tap/ca.pem
examples/mip-tap/main.c

Removed the pcap overhead and just added code to open a specific /tun/tap device instantiation (so things are easier to handle).

Add example to use TAP interface on Linux

---

mongoose.c
src/net.c

Or do you prefer the shorter but multiple exit version with `if (t == NULL) return NULL;` ?

Fix issue #1737

---

examples/udp-ssdp-search/main.c

This fixes a bug in the `udp-ssdp-search` example which causes all responses to be reported with the contents of the first response.
Note that in most cases the bug will probably be masked by the choice of search target (`urn:schemas-upnp-org:device:MediaRenderer:1`). Changing the target to `ssdp:all` makes the difference in behaviour easier to observe. 
Example output before change:
```
andrew in mongoose/examples/udp-ssdp-search > ./example
4be84767 2 main.c:45:tfn                Sending M-SEARCH
4be8476b 2 main.c:16:fn                 Got a response
SERVER -> Synology/DSM/192.168.0.3
LOCATION -> http://192.168.0.3:5000/ssdp/desc-DSM-eth0.xml
4be8478e 2 main.c:16:fn                 Got a response
SERVER -> Synology/DSM/192.168.0.3
LOCATION -> …
```

Fix SSDP example for second and subsequent responses

---

mongoose.c
mongoose.h
src/license.h

`GPL-2.0` was deprecated in favor of `GPL-2.0-only`.
`GPL-2.0+` was deprecated in favor of `GPL-2.0-or-later`.
See: https://spdx.org/licenses/

Update GPL license identifier

---

examples/raspberry/raspberry-pi-pico-w/Makefile

The user has to clone the repo, then edit the Makefile to change WiFi credentials. Running make build does both and the tests go flawlessly.
The user can run make to clone the repo, then change credentials and run make build, it will skip cloning if the repo is already there.
In some systems the compiled files are not owned by the user as Docker runs as root, so we first invoke clean in the cloned repo (which erases the compiled files), and then remove the cloned repo that the user owns and can rm.

Dettach git clone and fix clean

---

mongoose.c
src/http.c

I think this `mg_hexdump` call was for debugging and is not needed anymore.

Remove mg_hexdump from deliver_chunked_chunks

---

mongoose.c
mongoose.h
src/arch_tirtos.h
src/sock.c

- Sockets were not being put in non-blocking mode as the setsockopt() call wasn't using SOL_SOCKET
- Do not include errno.h but serrno.h, otherwise error codes are mangled... NDK functions use serrno, errno belongs to the compiler
- UDP sockets require binding to receive responses
- select() does not return write-ready on connect if the amount of bytes that can be written is below the "low-water mark". This parameter defaults to 2048, there was some code apparently setting this otherwise, with no success. Reworked the code to set this water mark at half the buffer size by just using plain getsockopt/setsockopt calls; otherwise TCP never connects if the TCP tx buffer size is set below 2048 (the example set it to 1024).
For the record:
TI typedef's void * SOCKET for internal use, …

Fix TI-RTOS port

---

mip/driver_stm32.c
mongoose.c

CR field is 3-bit long in F4 and F7
We've been losing the MSB and so setting it at zero instead of 4

CR incorrectly set in STM32 driver

---

mongoose.c
src/mqtt.c

Zero-length payload messages are valid messages, they can be sent with regular clients (mosquitto_pub -m "" or -n) and are fond to occur when a producer "deletes" a retained message and the consumer does not start with a clean session.
resolves #1827

Accept zero-length payload messages

---

examples/stm32/nucleo-f429zi-baremetal/mcu.h

We've already been there with the F7 (see #1694)
APB1_PRE and APB2_PRE are just index values 
https://github.com/cesanta/mongoose/blob/e580d4e637a65c354a8def8ece8aaa48a7572782/examples/stm32/nucleo-f746zg-baremetal/mcu.h#L19-L22
These index values represent a divisor, for example the index 5 is a /4 and the index 4 is a /2
Each UART can take the clock from APB1 or APB2, which can be /4 or /2.
This example uses UART3, which uses APB1 (not APB2), which is /4, and coincides with the index 4 that is the value of APB2_PRE. So, the fact that '4' and APB2_PRE are igual is just a coincidence.
https://github.com/cesanta/mongoose/blob/e580d4e637a65c354a8def8ece8aaa48a7572782/examples/stm32/nucleo-f746zg-baremetal/mcu.h#L180-L181
So, we either leave this as a hardcoded value or write code to turn …

Fix wrong reference to prescaler

---

mip/mip.c
mongoose.c
mongoose.h

An IP address is not local if it does not belong in the local address space.
The local address space is the local IP address anded with the IP mask.
The destination IP address is then anded with the IP mask and if it resides in the local address space, both should be equal. Probably there is a more performant way to do this.
clang format added some artifacts, and now that the TM4C driver has been merged, mongoose.[ch] include it

Fix incorrect local network address detection

---

.github/workflows/test.yml
examples/zephyr/Makefile

This:
- clones the Zephyr repo (west init)
- edits the YAML manifest (west.yml) to leave only those HALs/projects of interest for the examples using yq (jq for YAML)
- loads those repos (west update)
- runs make build on each example directory in sequence, so all of them use this trimmed Zephyr repo
This magic is done with a Makefile at the examples/zephyr directory. The regular user will follow the tutorials but we can take advantage of this Makefile to also have a reduced zephyrproject directory. We can run `make zephyr` there and just `make build` on the example of interest. This requires having `yq` installed (and calling with sudo in some systems; or calling with `YQ=`...). For the GA tests, yq is run as an action as provided by its author.
https://github.com/mikefarah/yq

Zephyr tests

---

examples/mip-tap/main.c

linux/if uses struct sockaddr that is defined in sys/socket.h. This breaks building on some systems (RHEL7). It went unnoticed as it was hidden by mongoose.h being included first

Add missing include

---

mongoose.c
src/net.c

closes #1870 
should we re-write this to avoid the tmp buffer now ?

Fix mg_straddr() stack overwrite

---

examples/stm32/nucleo-f429zi-freertos-mip/Makefile

The construction `*.c` works OK on Un*x derivatives but fails on Windows, as it is the shell who expands the wildcard.
The construction `$(wildcard *.c)` seems to work everywhere as it is make who expands the wildcard.

Fix wildcard in Makefile

---

mip/mip.c
mongoose.c

Like e.g.: at startup when sending DHCP Request
Returning a broadcast MAC from the cache lookup avoids this behavior

Fix sending ARP request for IP broadcasts

---

examples/ti/ek-tm4c1294xl-freertos-mip/FreeRTOSConfig.h
examples/ti/ek-tm4c1294xl-freertos-mip/Makefile
examples/ti/ek-tm4c1294xl-freertos-mip/boot.c
examples/ti/ek-tm4c1294xl-freertos-mip/link.ld
examples/ti/ek-tm4c1294xl-freertos-mip/main.c
examples/ti/ek-tm4c1294xl-freertos-mip/mcu.h
examples/ti/ek-tm4c1294xl-freertos-mip/mongoose_custom.h
examples/ti/ek-tm4c1294xl-freertos-mip/syscalls.c
mip/driver_tm4c.c
mongoose.c

Had to modify the driver to avoid name clashes (now I understand those name changes you introduced on the STM driver)
Latest forced push is just in case the mac filtering requires a rebase

Add FreeRTOS + MIP example on TM4C

---

mip/mip.c
mongoose.c
test/driver_mock.c
test/mip_test.c
test/unit_test.c

Stage 1: Add test. Passes on unit_test, fails on mip_test (forced push was to make VC98 happy)
Stage 2: Fix it.
Note: driver_mock rx func was returning len, that aparently caused MIP to allocate memory and the sanitizer would complain. Modified the driver to return 0.
Q: The order of calling is not being respected, POLL is now fired after a possible data event
Q: Should we move these common tests to a common file called by both unit and mip_test ? Do you expect more common tests to follow ? (We are now testing UDP with DHCP, we could run the SNTP test; we test TCP with the HTTP fetch)

MG_EV_POLL generation on MIP

---

examples/stm32/nucleo-f429zi-freertos-mip/Makefile
mip/driver_stm32.c
mongoose.c

- Frames are now read in order, and only host owned descriptors are checked
- Read as many frames as possible (but don't loop forever)
- Discard bad frames
- Improved exit out of suspended condition
- If a frame arrives while processing, it will now generate a new interrupt (formerly it would wait for another frame to arrive as we reset the flag on exit)
siege varies a lot but seems to give numbers 10% higher on average with this mods: ~200 tps to /api/hi on both F429 and F746
_**NOTE**: removing printf() from the driver exposed an issue in the order of gcc parameters in the F429-freertos-mip example Makefile, causing a linkage problem; so the modified Makefile..._

Improve STM32 driver

---

mip/driver_tm4c.c
mongoose.c

- Fix clock guessing
- Frames are now read in order, and only host owned descriptors are checked
- Read as many frames as possible (but don't loop forever)
- Discard bad frames
- Fixed incorrect handling of RU bit and exit out of suspended condition
- If a frame arrives while processing, it will now generate a new interrupt (formerly it would wait for another frame to arrive as we reset the flag on exit)

Improve TM4C driver

---

.github/workflows/test.yml
test/unit_test.c

armhf builds with unit_test runtime.
arm build is has no runtime since send() is not implemented.

Fix arm and armhf test builds and unit_test runtime.

---

mip/mip.c
mongoose.c

- We start a timer when we need to send an ACK.
- If a segment is sent before the timer expires, that timer is not reset
- We restart the keepalive timeout on send only if there was no ACK timeout pending
This patch always restarts the keepalive timeout on send. If there was a pending ACK, it will be sent piggybacked with this segment, so we avoid the dup ack; the keepalive message will be sent if there are no further msgs from this one
Note: the current keepalive strategy is two-way, we only check for no reception when we need to send. It will work as long as we are not streaming and that is not likely... If we have a partially closed socket scenario where we can send but the other end can't, we won't detect it until we stop sending. If we can't send but the other end can, we won't …

Avoid duplicated ACKs

---

mip/mip.c
mongoose.c

We ask for gw MAC address as soon as we get its IP address from DHCP.
In environments with noticeable frame loss, that response sometimes gets lost. We no longer ask, so when trying to send packets to the router, we end up sending broadcasts, that don't reach its destination.
Now if we need to send to the router and we don't have its MAC, we ask for it.

Ask for gw mac when needed and not known

---

examples/websocket-server/main.c

rest api is available at `/rest` and not `/api/rest`

Update comment for the path of rest API

---

examples/stm32/nucleo-f429zi-baremetal/boot.c
examples/stm32/nucleo-f429zi-baremetal/main.c
examples/stm32/nucleo-f429zi-baremetal/mcu.h
examples/stm32/nucleo-f429zi-freertos-mip/main.c
examples/stm32/nucleo-f746zg-baremetal/boot.c
examples/stm32/nucleo-f746zg-baremetal/main.c
examples/stm32/nucleo-f746zg-baremetal/mcu.h

Fix comments in newer mip initialization (main.c)
Correct stack initialization (boot.c)
Remove SCC clock enable when not needed (mcu.h)

Minor tweaks in STM32 examples

---

examples/rp2040/pico-rndis-dashboard/main.c
examples/stm32/nucleo-f429zi-usb-rndis/main.c
examples/stm32/nucleo-f746zg-usb-rndis/main.c
mip/driver_stm32.c
mip/driver_tm4c.c
mip/mip.c
mip/mip.h
mongoose.c
mongoose.h
test/mip_tap_test.c

- mip_rxcb() --> mip_qwrite()
- MIP no longer reads the queue, it just calls the driver rx()
- provided a default rx(): mip_driver_rx() so drivers don't need to implement the obvious. This function calls mip_qread()
- introduced mip_qread(), calls q_read()
- Since .rx in mip_if is always filled, MIP can no longer know if the queue will be used.
- Moved the queue initialization to each driver that uses it; if the user does not fill queue.len, the driver will.
- Added `.rx = mip_driver_rx` in existing drivers (stm32, tm4c) and RNDIS examples (F4, F7, Pico)
- Tested all affected examples for compilation and Pico, TI, F4 for execution

Rename mip_rxcb to mip_qwrite, add mip_qread and enforce rx() for drivers

---

mip/mip.c
mongoose.c

Close connection on incoming RST
Send RST when receiving data on nonexistent connections (was this avoided due to DoS attacks ?)

Handle TCP RST

---

mip/mip.c
mongoose.c

Use the "idle connection" definition of RFC-1122 4.2.3.6 (no reception from the other end)
Send keepalives on idle condition
Avoid sending a keepalive just when dropping the connection on inactivity
Reset time and miss count on reception
As ACK timer is shared, when cancelling an ACK timer (piggybacking on a sent frame), transform it into a keepalive timer
Fix no timer initialization in clients (would send a keepalive on connect)
Use settmout() to initialize timer on servers
Follow up to (and obsoletes the comment in) #1912

TCP keepalives

---

src/tls_openssl.c

After this (https://github.com/cesanta/mongoose/commit/d76f86f7db59838fa4a2727d7d07710c6cf7470c) change, `SSL_set_tlsext_host_name` is missing, and SNI (Server Name Indication) did not work.
In that commit `SSL_set_tlsext_host_name` is replaced by `SSL_set1_host`, but the both are not same. `SSL_set_tlsext_host_name` is for SNI and `SSL_set1_host` for certification.
This pull request adds `SSL_set_tlsext_host_name` aside `SSL_set1_host` in the `tls_openssl.c`.

Bugfix OpenSSL TLS SNI

---

mongoose.c
mongoose.h
src/dns.c
src/net.c
src/net.h
src/sock.c
src/tls_mbed.c
src/util.h
test/unit_test.c

Our mg_*printf API has a non-standard extensions: `%M`, `%I`, `%H`, `%A`, etc etc.
We might want more functionality.
For example, we currently have `%Q` specifier for double-quoted string - we might want to add a non-quoted variant for strings, to handle cases e.g. `mg_printf(c, "{%Q: \"hello, %q\"}", "message", "escape, but not quote");` 
Extra functionality is good.
But non-standard is bad.
We should move towards using a minimum non-standard features.
This PR makes `%I` specifier not needed anymore:
Before:
```c
mg_printf(c, "%I", c->rem.ip);  // Prints IPv4 address. Caller must be sure it is IPv4
```
After:
```c
mg_printf(c, "%M", mg_print_ip, &c->rem);  // Prints IP address, IPv4 or IPv6
```
This PR cleans up `%I` usage in `src/` and `test/`. 
Examples, and README still have `I%`

Add mg_print_ip, mg_print_ip_port helper functions

---

mip/mip.c
mongoose.c
mongoose.h
src/util.c
src/util.h

util.c:  Added mg_print_ip4 (and mg_print_ip6) as it was needed by MIP. Refactored mg_print_ip to use it
#1996 #1997

Do not use %I %A in MIP

---

mip/mip.c
mongoose.c

Do not call `mip_rx()` when the driver returns 0 (no frame)
`mip_qread()`: Do not `qpmark()` when there are no frames in the queue (driver using `mip_qread()` as its `_rx()` function)

qprofile related fixes

---

mongoose.c
src/tcpip/tcpip.c

Architectures and devices with a true RNG, won't be affected. Ephemeral port initial selection works OK on those.
For others, this adds a bit of entropy.
The pseudo-random generator is reseeded on link up and again on DHCP reception (crafting from the former value).

Seed fallback clib PRNG with some entropy

---

mongoose.c
src/http.c

closes #2069 
[RFC-2616](https://www.rfc-editor.org/rfc/rfc2616#section-4.1): header fields are separated by \r\n
Content-length number was incorrectly overwriting the \r in the end-of-header sequence, leaving only a \n
Before this PR:
```
Content-Length: 10         \n
\r\n
```
After this PR:
```
Content-Length: 10         \r\n
\r\n
```

Fix content-length header in mg_http_reply()

---

examples/stm32/nucleo-f429zi-baremetal/syscalls.c
examples/stm32/nucleo-f429zi-rndis/syscalls.c
examples/stm32/nucleo-f746zg-baremetal/syscalls.c
examples/stm32/nucleo-f746zg-rndis/syscalls.c
examples/stm32/nucleo-h743zi-baremetal/syscalls.c

After following the source code learned that we need to return -1 when the heap is exhausted
The strange crash after applying the fix was arm gcc 11.3 fault when malloc() tried to beg some memory out of the freed list.
Latest 12.2 works OK
Not applying to FreeRTOS examples as it has its own heap limit

Fix _sbrk()

---

examples/rp2040/pico-rmii/driver_rp2040_rmii.c
examples/rp2040/pico-rmii/main.c
mongoose.c
mongoose.h
src/tcpip/tcpip.c
src/tcpip/tcpip.h
src/util.c

Add option to check MAC, defaults to off (not checking from now on as most controllers do that for us)
Add option to check CRC, defaults to off (most controllers do that for us)
Re-allow driver to set queue size
Improve `mg_crc32()`
Remove `mg_tcpip_driver_rx()`
Fix removed `mg_tcpip_qread()` still showing up in `tcpip.h`

Update RMII example, enhance MIP

---

examples/stm32/nucleo-f429zi-freertos/mongoose_custom.h
examples/stm32/nucleo-f746zg-freertos/mongoose_custom.h
examples/ti/ek-tm4c1294xl-freertos/mongoose_custom.h

#2128 adds inclusion of errno.h when lwIP is not added to MG_ARCH_FREERTOS

Remove no longer necessary includes

---

mongoose.c
mongoose.h
src/arch.h
src/arch_rtx.h
src/sock.c
src/util.c

Remove MG_ARCH_RTX
Add MG_ARCH_CMSIS_RTOS1, serving Keil RTX and adding a timebase function
Add MG_ARCH_CMSIS_RTOS2, serving Keil RTX5 and FreeRTOS (through API v2) and adding a timebase function
Fix a socket call that actually belongs to MDK (RL), not RTX

Add arch for CMSIS-RTOS v1 and v2

---

mongoose.h
src/net_ft.h

Fix using error codes from errno.h:
- FreeRTOS-Plus-TCP uses its own prefixed constants. Values usually coincide with those in errno.h, but...
- Keil's errno.h is minimal and does not include EWOULDBLOCK, etc

Let FreeRTOS-Plus-TCP build on Keil

---

examples/multi-threaded/Makefile

Many Linux distro gcc compilers require `-lpthread`
closes #2148 
On Windows, MinGW warns:
```
main.c: In function 'start_thread':
main.c:21:16: warning: cast between incompatible function types from 'void * (*)(void *)' to
void (*)(void *)' [-Wcast-function-type]
21 |   _beginthread((void(__cdecl *)(void *)) f, 0, p);
|                ^
```
though the cast is OK and works OK, so I disabled it

Fix for some compilers

---

mongoose.c
src/tcpip/tcpip.c

Add UDP processing to mg_io_send(), it would send TCP packets out of the blue instead of UDP datagrams

Fix mg_xprint() for UDP in MIP

---

mongoose.c
src/tcpip/tcpip.c

An UDP listener wanting to send a response didn't have the other end MAC address, so responses were being sent to an all-zeroes MAC.
We take it as it is on each received datagram (as we do with IP and port). Perhaps there is a faster way of copying it, but checking for an empty slot is certainly slower...
Fixes #2164

Fix UDP listeners in MIP

---

examples/http-reverse-proxy/main.c

Fix #2190 
Since no reply is sent, `c->is_resp` remains set and further requests on the same connection in keep-alive mode are ignored.
Clearing this flag once a response has started to be written allows further processing and fixes this.

Fix http-reverse-proxy for keep-alive incoming connections

---

mongoose.c
mongoose.h
src/http.c
src/str.c
src/str.h
test/unit_test.c

Handling numbers outside int64_t range requires overflow indication, as 0 can be valid in some circumstances
Modified `mg_to64()` and `mg_tou64()` to be passed a `bool *` and set it to true on error. A `NULL` can be passed when not interested.
Changed `mg_http_parse_headers()` to use `mg_to64()`, as all numbers of interest will be `>= 0`, we exit on error indication
Modified the number parsing to accomodate a closer to full range interval
Passed `NULL` in other invocations of `mg_to64()`
Added further checkings in `unit_test.c`, both for `mg_to64()`/`mg_tou64()` and for incorrect/unhandled `Content-length`s

improve negative Content-length handling

---

examples/stm32/nucleo-f746zg-freertos-tcp/main.c
examples/stm32/nucleo-f746zg-keil-baremetal/main.c
examples/stm32/nucleo-f746zg-keil-freertos-lwip/main.c
examples/stm32/nucleo-f746zg-keil-freertos-tcp/main.c
examples/stm32/nucleo-f746zg-keil-freertos/main.c
examples/stm32/nucleo-f746zg-keil-freertos_cmsis2-lwip/main.c
examples/stm32/nucleo-f746zg-keil-freertos_cmsis2/main.c
examples/stm32/nucleo-f746zg-keil-rtx-mdk/main.c
examples/stm32/nucleo-f746zg-keil-rtx/main.c
examples/stm32/nucleo-f746zg-keil-rtx5-lwip/main.c
examples/stm32/nucleo-f746zg-keil-rtx5-mdk/main.c
examples/stm32/nucleo-f746zg-keil-rtx5/main.c

and fix examples/stm32/nucleo-f746zg-keil-freertos_cmsis2

standardize header inclusion

---

mongoose.c
src/mqtt.c

#2220 
- Properly respond with PUBREC to QoS2 messages (instead of PUBACK)
- The user event handler will still get a message on PUB, so it should store it and catch `MG_EV_MQTT_CMD`, ignoring possible retransmissions of the same msg until it gets PUBREL
Current status:
- For both QoS1 and QoS2, the user event handler should store the msg to be sent and catch `MG_EV_MQTT_CMD`, until it gets PUBACK (for QoS1) / PUBREC (for QoS2) and eventually retransmit on timeout. (QoS2 would also involve setting the DUP bit IIRC)
Should we update our example to show how to do this ?

fix qos=2 handling

---

mongoose.c
src/mqtt.c
test/unit_test.c

- Fix a bug when sending PUBACK/PUBREC in MQTT5: one extra byte sent and no props.
- Note:   According to MQTT5 3.4.2-1: _The Client or Server sending the PUBACK packet MUST use one of the PUBACK Reason Codes [MQTT-3.4.2-1]. The Reason Code and Property Length can be omitted if the Reason Code is 0x00 (Success) and there are no Properties. In this case the PUBACK has a Remaining Length of 2._ (3.5.2-1: idem for PUBREC).
- We don't actually need to do as we are doing now, sending empty props and reason code = 0, I assume that is for future expansion
- Add bare minimum (MQTT5-compatible) support for handling PUBREC and PUBREL in order to ease testing and customer implementation of QoS2 (both sending and receiving)
- Modify the unit_tests to show a conceptual way of handling different QoS
- …

MQTT QoS + v5

---

src/net_rl.h

https://www.keil.com/pack/doc/mw/Network/html/group__using__network__sockets__bsd__func.html
`accept()`:
> In blocking mode, which is enabled by default, this function waits for a connection request. In non blocking mode, you must call the accept function again if the error code BSD_EWOULDBLOCK is returned.

RL: fix accept() not looping on BSD_EWOULDBLOCK

---

mongoose.c
src/tcpip/driver_stm32.c

Apparently in some micros, depending on the compiler, descriptors are still being written when the DMA registers are configured to start tx. This commit inserts a DSB to prevent that.

Improve driver

---

mongoose.c
mongoose.h
src/tcpip/tcpip.c
src/tcpip/tcpip.h

- Use IP only after DHCPACK
- Correct DHCPREQ datagram format according to RFCs
- broadcast destination addresses required for initial and rebind messages, server is identified via options
- renew/rebind messages must not include addresses in options but fill `ciaddr`
- Handle DHCPNACK and lease expiration time (forget address and restart)
Renew function remains TODO, requires storing server address and handling time differently.

improve DHCP in MIP

---

.github/workflows/test.yml
mongoose.c
mongoose.h
test/unit_test.c

Test with no TLS, with select() and poll().
Do not retest when using TLS (use default epoll for Linux, poll for MacOS, select for Windows).

Optimize test coverage

---

mongoose.c
src/net_builtin.c

Adding ARP lookup exposed shadowed local broadcast handling (broadcast address was taken as local address and fired an ARP lookup). So, check is done now _before_ checking for local addresses.
Added also global broadcast MAC resolution.
Should we disallow users from sending global broadcasts ?
Fixes #2396

send broadcasts in MIP

---

mongoose.c
mongoose.h
src/config.h
src/log.c

Allows customers to redefine their own `mg_log_prefix()` and `mg_log()` functions, to completely change logging logic.

Add MG_ENABLE_CUSTOM_LOG

---

src/drivers/stm32h.c
src/drivers/tm4c.c

Some drivers were not counting "no DMA descriptors available on tx" errors

honor ifp->nerr

---

examples/stm32/nucleo-h743zi-make-freertos-builtin/FreeRTOSConfig.h
examples/stm32/nucleo-h743zi-make-freertos-builtin/main.c

Startup code takes two long to clear RAM, SystemInit is called right after reset, so sometimes SysTick fires before FreeRTOS has fully initialized

Fix H743 FreeRTOS early SysTick crash

---

mongoose.c
mongoose.h
src/drivers/same54.c
src/drivers/same54.h

I've verified the UI, works as expected

Fix #2487 - correct GMAC_DCFGR, receive size -> full size

---

examples/mqtt-over-ws-client/main.c

If the MQTT over WS broker is not port based, that is, it does not assume that the protocol carried by the WebSocket connection will be MQTT based on the port number, then, if we can't change it, we need to add an extra header in the connection request, in order to negotiate that: `Sec-Websocket-Protocol: mqtt`
Many clients default to doing that, so maybe we should also default to that in our example

make Mosquitto happy

---

mongoose.c
mongoose.h
src/net.c
src/net.h
src/net_builtin.c
src/sock.c
src/tls_builtin.c
src/tls_mbed.c
src/tls_openssl.c
src/tls_openssl.h
test/fuzz.c
test/unit_test.c

The reason for this PR is to minimise the amount of data copies for the TLS case. TLDR: raw data is now received in the `c->rtls` IO buffer, and can be accessed directly. 
So, receive path:
`stack receives new raw data -> c->rtls -> (TLS decrypt) -> c->recv`
Note that the send path does not have the same. Apparently, TLS implementation can just encrypt data (`mg_tls_send()`) data on-the-fly.
Right now, the builtin receive path looks like this:
1. Stack. Packet data gets copied to the s->raw IO buffer
2. Stack. Call mg_tls_recv
3. TLS. mg_tls_recv copies data in its own recv buffer
4. TLS. mg_tls_recv decrypts the data and returns
5. Stack gets decrypted data and copies into c->recv
This PR unifies receive path to all TLS implementations by creating `c->rtls` IO buffer for the raw, …

TLS layer: c->rtls to optimise recvd TLS data

---

examples/stm32/nucleo-h743zi-make-baremetal-builtin/hal.h
examples/stm32/nucleo-h743zi-make-baremetal-builtin/main.c
examples/stm32/nucleo-h743zi-make-baremetal-builtin/sysinit.c

Some other changes apart of moving:
1. Changed non-portable asm("DSB") to the portable __DSB()
2. Moved syscfg init to the ethernet_init() - cause ethernet init uses syscfg
3. Moved SystemInit() to  main.c - cause it became really tiny

Move clock_init() to hal.h

---

examples/device-dashboard/Makefile
examples/stm32/nucleo-f746zg-make-baremetal-builtin/Makefile

Followup addressing comments in #2538
Avoid clashes with other TLS libs
Current docs instruct to build with no TLS and with mbedTLS (and openSSL); we'll soon default to build with our built-in TLS code, so at that point we would need to address any other changes again.
Any example can be built with our built-in TLS using `CFLAGS_EXTRA="-DMG_TLS=MG_TLS_BUILTIN"`

default again to current doc defaults

---

mongoose.c
src/net_builtin.c

Fallback to IP source address on DHCP servers not filling sid

---

mongoose.c
src/sock.c

Mongoose reads raw encrypted data into the c->rtls buffer. Then, it feeds that data to the TLS library.
Currently, if server finished sending the data, it closes the connection. Mongoose reads data into c->rtls, so c->rtls has some data to be decrypted, then Mongoose reads 0 from the socket, indicating that server has closed the connection.
And Mongoose closed the connection too, despite it has some data in c->rtls yet to be decrypted!
This PR fixes that issue and decrypts everything before closing the connection.

Fix #2570: close only when TLS buffers drained

---

examples/file-upload-multiple-posts/main.c
examples/file-upload-multiple-posts/web_root/app.js
mongoose.c
mongoose.h
src/fs.c
src/http.c
src/http.h
src/str.c
test/unit_test.c

This PR also fixes a bug in `mg_path_is_sane()`, and adds unit tests for it

Allow user specify file in mg_http_upload

---

mongoose.c
src/dns.c

Fixes #2600 
Instead of just rejecting records with more than 15 answers (formerly 10), limit ourselves to process no more than 10 of them; that is quite larger than the more deeply nested found so far (4). Works with the OP reference.
Reason: we can go rising the accepted number and nets may keep adding servers and providing lots of responses. We handle a reasonable number to get buried aliases for most known cases so far.

cap # responses instead of rejecting

---

test/unit_test.c

Break current tests due to #2617 
#2620 fixes this

test returned content-type for custom 404

---

mongoose.c
src/mqtt.c

fixes #2700 
closes #2701, mg_str is size_t and comparison for >= 0 makes no sense, hence some compilers or static analyzers would warn about that.

Allow zero-length 'last-will' messages

---

mongoose.c
mongoose.h
src/mqtt.c
src/mqtt.h
test/unit_test.c

#2689 
- Should work as long as the id counter does not rollback (65536 messages sent while waiting to retransmit)
- Does not break current API

add simple API support for app MQTT pub retries

---

test/fuzz.c

fix fuzzer

---

.github/workflows/nightly.yml
mongoose.c
src/mqtt.c
src/tls_openssl.c
src/tls_x25519.c
src/util.c
test/Makefile

- Added Makefile wolfSSL build option with `SSL=WOLFSSL`
- Fixed missing BIO symbol errors
- Rename `fe` to `mg_fe` as it collides with `fe` defined in `wolfssl/wolfcrypt/fe_operations.h`
- `byte` variable name shadows the wolfSSL `byte` type
-  Updated nightly to run wolfSSL tests
Tested with `make test`

Add wolfSSL support

---

mongoose.c
src/tls_uecc.c

Zephyr warns about these being redefined, as they have their own in an "utility macros" header

avoid redefinitions

---

mongoose.c
src/tls_builtin.c

CHACHA20 buffering code reserves 8KB stack space for temporary decryption room.
This is not enough, as messages can be above 16K when receiving files above that size.
This PR removes that stack strain (our docs instruct to have an 8KB stack space and these wouldn't be enough when using our built-in TLS) and places it on the heap, allocating as much as needed for that particular message size.

fix stack trashing

---

mongoose.c
src/tls_builtin.c

When receiving more than 1 TLS record, that is content > 16K, data is buffered in rtls until a full record is received. This buffer grows at MG_IO_SIZE units when needed.
At this point, our built-in TLS marks a record has been found and holds a pointer to rtls stored in tls->recv. It decrypts and transfers to recv MG_IO_SIZE units.
As more data arrives, rtls is resized again, been freed and re-alloc'ed. But our built-in TLS still has a pointer to the freed content.
This works as long as the content stays there, but eventually triggers some complex failure mechanism.
This PR rewrites the TLS code to store and work with an offset instead. There is no performance penalty, some RAM saved, and there are no dependencies on buffer management.
NOTE: This has been opaqued by #2807 that limits the …

Refactor tls receive pointer scheme (fix read after free)

---

examples/nxp/rt1060-evk-make-baremetal-builtin/hal.h
examples/nxp/rt1060-evk-make-freertos-builtin/hal.h
mongoose.c
src/drivers/phy.c

These PHYs have a strap to set the default value for the ISO (isolation) bit in the control register.
NXP documentation says default is to disable, but a closer look at the schematics reveals it is not. The respective pin is pulled-up, in spite of the text saying it defaults to pull-down.
This has been opaqued while we did not respect hw defaults (how the end user has designed the board to be strapped). Since this bit is useless to keep set, this PR overrides that setting
Unrelated fixes in comments also included

Patch KSZ PHY for NXP

---

mongoose.c
src/fmt.c
test/unit_test.c

Revert "fix printf precision handling"

---

mongoose.c
src/sock.c

Even though we receive IO_ERR, several outstanding TLS records can lie in our buffer. One or two extra calls is not enough to correctly process them and cleanly close.
NOTE: is_io_err becomes unused, will be removed further on if this proves to be the final battle.
fixes #2885 
closes #2668 
PS: In rare cases, rtls was filled with more than one record, and our capping strategy prevented us to call mg_tls_recv(). Fixed.

Fix multiple TLS records in buffer

---

mongoose.c
mongoose.h
src/tls_aes128.c
src/tls_aes128.h

Avoid adding "shorter types" that clash with others and generate warnings (armcl)

avoid trashing other projs thinking redefining types is convenient

---

mongoose.c
src/ota_imxrt.c

The compiler decided to use memset/memcpy in flexspi_nor_get_config function, which will lead to a crash during the firmware swap when we erase the sector in which stdlib resides.
I rewrote this function to make sure this optimization does not happen.
Removed sector allocation from single_bank_swap.
Added MG_IRAM to flash_wait.

RT1020 OTA: removed unnecessary compiler optimisation

---

mongoose.c
mongoose.h
src/ota.h
src/ota_stm32h7.c

I encountered an issue while testing that prevented OTA from working properly on dual core H7 devices (H755 and H745).
These devices normally boot from both cores. CM4 requires by default a firmware at address 0x08100000 and CM7 requires a firmware at address 0x08000000.
The issue is we are using address 0x08100000 to store the new firmware, which means that after the next reset, both cores will start executing their corresponding firmwares. I noticed this always leads to a crash and the board gets bricked after this...
I put up a fix to disable CM4 from executing before resetting.

H7 dual core OTA fix

---

mongoose.c
src/http.c

15.5.12. 411 Length Required
The 411 (Length Required) status code indicates that **the server** refuses to accept the request without a defined Content-Length (Section 8.6). The client MAY repeat the request if it adds a valid Content-Length header field containing the length of the request content.
fixes #2969

Fix issuing 411 responses as a client

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Mongoose Guru](https://gurubase.io/g/mongoose) to Gurubase. Mongoose Guru uses the data from this repo and data from the [docs](https://mongoose.ws/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Mongoose Guru", which highlights that Mongoose now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me …

Introducing Mongoose Guru on Gurubase.io

---

mongoose.c
src/tls_builtin.c
src/tls_mbed.c
src/tls_openssl.c
tutorials/smtp/smtp-client/main.c

`mg_tls_handshake()` from built-in TLS was not firing the `MG_EV_TLS_HS` event; the SMTP example was not working because of this. Fixed
We seem to have leftovers from our attempt to make TLS start automagically:
`mg_tls_init()` in both MbedTLS and OpenSSL had `if (c->is_client && c->is_resolving == 0 && c->is_connecting == 0) mg_tls_handshake(c);`. Built.in TLS did not do this. Obviously c->is_resolving = 0 and c->is_connecting = 0 at client connect, when mg_tls_init() is called. Besides that, connect_conn and its MIP equivalent call mg_tls_handshake(c) right after the event call to EV_CONNECT returns.
Removed

fix built-in TLS not calling MG_EV_TLS_HS; uniformize mg_tls_init()

---

examples/pico-sdk/pico-2-w-picosdk-freertos-lwip/CMakeLists.txt
examples/pico-sdk/pico-2-w-picosdk-freertos-lwip/Makefile
examples/pico-sdk/pico-rmii/CMakeLists.txt
examples/pico-sdk/pico-rndis-dashboard/CMakeLists.txt
examples/pico-sdk/pico-rndis-device/CMakeLists.txt
examples/pico-sdk/pico-w-picosdk-freertos-lwip/CMakeLists.txt

Fixes #3027 via cloning a development branch at a specific spot.

Fix Pico-SDK aggressive optimization breaking OTA

---

examples/stm32/nucleo-g031-make-baremetal-builtin/main.c

Our usual implementation of `mg_millis()` in our HALs, just reads an `uint64_t` that is incremented on interrupts.
In some platforms, like ARM v6-M (Cortex-M0, M0+), there is no way to atomically read a 64-bit quantity, so an interrupt could occur while reading its 32-bit components. This gets worse with 16- and 8-bit architectures; the effects are described in [this article](http://www.scaprile.com/2022/04/17/on-atoms-and-clocks/)
The probablity of this happening is very low on 32-bit systems, but it is not zero, so it can cause glitches on always-on systems.; the 32-bit low word rolls over every ~50 days, a 16-bit one every ~1 minute and so on, though the errors introduced are less significative (the 8-bit LSB rolls over every 256ms but an error here is of the same magnitude), but …

no LDRD in v6-M

---

mongoose.c
mongoose.h
src/sock.c

Windows actually returns IO_RESET instead of IO_ERR when the remote end sets the TCP RST flag
#3031

Fix Windows returning IO_RESET

---

mongoose.c
src/drivers/tms570.c
src/drivers/xmc.c
src/drivers/xmc7.c

Small tweaks to RX logic on some of the drivers to use our initial scheme for older drivers (following discussions in PR #3039)

ETH driver: use the same scheme for RX

---

mongoose.c
src/net_builtin.c
src/tls_builtin.c

ASAN was reporting undefined behaviour (UB).
```
src/net_builtin.c:655:37: runtime error: applying zero offset to null pointer
```
Weird as it seems, `&io->buf[io->len]` is UB in C and in C++ < C++17 for a NULL pointer, even if the offset is 0. This condition happens at TLS receive start time, when TLS has not yet decrypted any record and hence no iobuf has been created for decrypted data.
Once this is fixed by eliminating the offset when the pointer is NULL, then the first time a record gets decrypted there is no buffer to hold data, it will be created at the next loop. when `mg_tls_avail()` will be called. We then pass a NULL destination pointer to `memmove()`, which, even though len is 0, will violate the specs and trigger ASAN again
```
src/tls_builtin.c:1385:11: runtime error: null …
```

fix UB and possible exception trigger

---

mongoose.c
mongoose.h
src/net.h
src/tls_builtin.c
src/tls_mbed.c
src/tls_mbed.h

When sending encrypted data, `mg_tls_send()` interacts with the proper library function, which in turn will call `mg_io_send()` to send data. The transport layer may fail to send all data and return an INPROGRESS/WOULDBLOCK/etc error code. What to do in that case depends on the TLS library being used
handles this internally
Failure is detected after encryption, so just returning that condition causes current call data to be buffered, with new data (if any) added next. Next call to mg_tls_send then re-encrypts this (old unsent data + possibly new added data), placing it after the already encrypted old data.
This PR returns the number of bytes encrypted on failure, as they have already been encrypted and ready to send. The wait condition is returned on next call, when we send outstanding …

fix IO_WAIT on send for builtin TLS and MbedTLS

---

mongoose.c
src/net_builtin.c

fixes #3098 
TCP segment handling was incorrectly discarding payload when FIN was set.

Fix handling of FIN segments carrying data

---

mongoose.c
src/net_builtin.c

- Add TCP options and announce MSS when sending SYN and SYN ACK (starting and accepting connections)
- Parse TCP options and accept peer announced MSS, honor it and cap TCP data sent, BUT, only when connecting.
- To be able to get MSS when accepting connections, we need some kind of backlog strategy

Handle (specific) TCP options

---

mongoose.c
src/net_builtin.c

041ec6e broke TLS handling and 3-way closure (see #3009 and 8de9699 (and prior related stuff, for that matter))
The closure logic is fine, the actual problem is that our TCP code is not formally a state machine and some things trigger others when they shouldn't, without us noticing.
In this case, **the uploading host attempted to POST a huge file, we tried to close, sent FIN and started our 3-way closure timer. The uploading host kept sending data, and each segment would incorrectly start an ACK timer, overwriting the FIN timer already in place. When this timer expired, we would ACK that data, so the uploading host would keep sending, and we trying to close, and restarting this until we run out of memory**.
_This fix ignores any attempts to set a new timeout once the FIN timeout has been …

fix broken TCP closure

---

mongoose.c

Currently if a URL being requested has a tilde in the path, the `clen()` of the tilde will be reported as 0, causing it to stop parsing.
Tildes are valid in URIs and don't have to be [percent-encoded](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding). It's less clear to me on whether ~ is a valid symbol in header values, but it doesn't seem like any standards preclude it.

Fix URIs or header values containing tildes being unparsable.

---

tutorials/http/uart-bridge/esp32/main/uart.c

From 5.2.5 on, `UART_HW_FIFO_LEN(no)` was introduced, and docs changed to it
Apparently, latest (at this time) has removed `UART_FIFO_LEN`, even though it can be found in the docs.
We're forced to check for IDF version to be able to handle many possible IDF versions used in Arduino, MicroPython...

handle IDF breaking UART API
